PluginController: Allow enabling / disabling plugins
MetaMask/snaps-skunkworks pull request #116
Opened 2021-11-02 19:30 UTC by shanejonas

This adds enable/disable functionality to the `PluginController`.

fixes #113

2021-11-02 19:53 UTC, shanejonas commented
One thing that I wanted some feedback on is wether or not calling disable should stop the plugin

2021-11-03 19:38 UTC, rekmarks requested changes
In addition to inline comments, we should add a docstring for `_transitionPluginState` and `pluginStatusStateMachineConfig` to explain what they are for, how plugin statuses work and should be used, and that we are using XState conventions.

2021-11-03 20:18 UTC, shanejonas commented on packages/controllers/src/plugins/PluginController.ts
> + * The StateMachine configuration for a plugins `status` state.
```suggestion
 * The state machine configuration for a plugins `status` state.
```

2021-11-03 20:33 UTC, rekmarks approved these changes
LGTM!

2021-11-03 20:38 UTC, merged