wip: refactor plugin + worker interface
MetaMask/snaps-skunkworks pull request #19
Opened 2021-06-04 18:53 UTC by shanejonas

this changes the interface names to not have `worker` in them, also changes the interface to them as to not require `workerId`, but use the `pluginName` instead

2021-06-14 18:07 UTC, shanejonas commented on packages/controllers/src/plugins/PluginController.test.ts
> +      terminateAll: workerExecutionEnvironment.terminateAllPlugins.bind(
```suggestion
      terminateAllPlugins: workerExecutionEnvironment.terminateAllPlugins.bind(
```

2021-06-14 18:08 UTC, shanejonas commented on packages/controllers/src/plugins/PluginController.test.ts
> +      terminateAll: workerExecutionEnvironment.terminateAllPlugins.bind(
```suggestion
      terminateAllPlugins: workerExecutionEnvironment.terminateAllPlugins.bind(
```

2021-06-14 18:08 UTC, shanejonas commented on packages/controllers/src/plugins/PluginController.ts
>    terminateAll: TerminateAll;
```suggestion
  terminateAllPlugins: TerminateAll;
```

2021-06-14 18:09 UTC, shanejonas commented on packages/controllers/src/plugins/PluginController.ts
>    private _terminateAll: TerminateAll;
```suggestion
  private _terminateAllPlugins: TerminateAll;
```

2021-06-14 18:36 UTC, rekmarks requested changes
This is a great start!

I have a couple of significant change requests that I left and explain inline.

In addition to those, I think it's worth considering how the current execution environment (EE) service interface will work when we have multiple EEs. Ideally, there should be a single EE service class that's capable of starting a plugin in any conceivable EE. In that paradigm, the worker EE service would be a sub-service of that uber-EE service. As I mention inline, I believe that some of the existing public methods of the service interface are too low-level for the plugin controller, but they would be completely appropriate for a class that manages multiple EE services.

2021-06-14 18:36 UTC, rekmarks commented on packages/controllers/src/services/PluginExecutionEnvironmentService.ts
> +  command: Command;
In line with my other comments, I think these make sense on this interface, but I they shouldn't be used by the plugin controller directly, if possible.

2021-06-15 18:08 UTC, shanejonas commented on packages/controllers/src/plugins/PluginController.test.ts
> +          return new Promise((resolve) => {
nit: could be `return async () => `${request.method}${request.id}``

2021-06-15 19:01 UTC, rekmarks requested changes
Looks great! Just a couple of things to iron out.

2021-06-15 22:30 UTC, rekmarks requested changes

2021-06-15 22:30 UTC, rekmarks commented on packages/controllers/src/services/WebWorkerExecutionEnvironmentService.ts
> +    this._mapPluginAndWorker(pluginData.pluginName, _workerId);
Ah! We should make sure that it's impossible to execute a plugin twice, by checking if it's already mapped at the top of this function. This is probably worthy of a test case, too.

```suggestion
  async executePlugin(pluginData: PluginData): Promise<unknown> {
    if (this.pluginToWorkerMap.has(pluginData.pluginName)) {
      throw new Error(`Plugin "${pluginData.pluginName}" is already being executed.`);
    }

    const _workerId = await this._initWorker();
    this._mapPluginAndWorker(pluginData.pluginName, _workerId);
```

2021-06-16 19:42 UTC, rekmarks approved these changes
LGTM! There are a couple of pre-existing issues I noticed during review that can be addressed during a follow-up.

2021-06-16 20:59 UTC, merged