Merged iframe and web workers together into a new package
MetaMask/snaps-skunkworks pull request #231
Opened 2022-02-08 16:27 UTC by ritave

After the new package is uploaded to npm we can remove workers package

2022-02-10 07:43 UTC, rekmarks commented
@ritave did you test the Web Worker environment on Flask in place of the iframe?

2022-02-14 15:44 UTC, ritave commented
@rekmarks 

> @ritave did you test the Web Worker environment on Flask in place of the iframe? That's not a requirement for this PR, but we'd want to confirm that it boots before closing #225.

Yeah I got it working. Ready for review

2022-02-14 23:51 UTC, shanejonas commented
the bundle seems a lot bigger:

```WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  iframe (346 KiB)
      iframe.bundle.js
  webworker (346 KiB)
      webworker.bundle.js
```

vs [70k](https://metamask.github.io/iframe-execution-environment/0.3.1/bundle.js)

is it the `resolve` for stream?

2022-02-15 19:10 UTC, shanejonas commented
ah ok it looks like its about the same size after gzipping:

<img width="1762" alt="image" src="https://user-images.githubusercontent.com/364566/154131898-a94eaefa-d311-4c7f-a23b-1c413a80256e.png">

2022-02-15 19:12 UTC, shanejonas commented on packages/execution-environments/src/openrpc.json
> +                "method": "hello",
```suggestion
                "jsonrpc": "2.0",
                "method": "hello",
```

2022-02-15 21:33 UTC, rekmarks requested changes

2022-02-15 21:33 UTC, rekmarks commented on packages/execution-environments/webpack.config.js
> +    plugins: [new NodePolyfillPlugin()],
We should ensure that SES lockdown is copied purely as in [the orignal implementation](https://github.com/MetaMask/iframe-execution-environment/blob/main/webpack.config.js#L35-L42), and added to `index.html` via its own `<script>` tag, which should also be the first script to execute.

2022-02-15 21:34 UTC, rekmarks commented on packages/execution-environments/src/common/lockdown/lockdown-more.ts
> +import 'ses';
Per my other comment, [`ses` should not be imported in this manner](https://github.com/MetaMask/snaps-skunkworks/pull/231/files#r807333562).

2022-02-15 21:51 UTC, rekmarks requested changes
Nicely done! Aside from the `ses` import / initialization stuff, my main feedback regards renaming ~this package and its~ the classes in this package to "snap executors" instead of "controllers".

2022-02-15 21:51 UTC, rekmarks commented on packages/execution-environments/LICENSE
> +Copyright ConsenSys Software Inc. 2021. All rights reserved.
nit:
```suggestion
Copyright ConsenSys Software Inc. 2022. All rights reserved.
```

2022-02-15 21:51 UTC, rekmarks commented on packages/execution-environments/README.md
> +Snap sandbox environments for executing SES javascript
```suggestion
Execution environments for [MetaMask Snaps](https://docs.metamask.io/guide/snaps.html), sandboxed using [Secure EcmaScript (SES)](https://github.com/endojs/endo/tree/master/packages/ses).
```

2022-02-15 21:51 UTC, rekmarks commented on packages/execution-environments/package.json
> +  "version": "0.1.0",
non-blocking: If we start the package at version `0.0.0`, it tends to work better with our release automation, although it probably doesn't matter for monorepos as long as the version is less than or equal to the highest version in the monorepo.

```suggestion
  "version": "0.0.0",
```

2022-02-15 21:51 UTC, rekmarks commented on packages/execution-environments/package.json
> +  "name": "@metamask/execution-environments",
I think we have an opportunity to improve on our previously established naming conventions here:

```suggestion
  "name": "@metamask/snap-executors",
```

2022-02-15 21:51 UTC, rekmarks commented on packages/execution-environments/src/common/BaseControllers.ts
> +export class BaseController {
In line with the suggested renaming of this package:

```suggestion
export class BaseSnapExecutor {
```

2022-02-15 21:51 UTC, rekmarks commented on packages/execution-environments/src/common/lockdown/lockdown.ts
> +import 'ses';
We should get rid of this `ses` import, too. For future reference, SES only needs to be imported once, and it mutates the global environment (realm) automagically when it's imported.

2022-02-15 21:51 UTC, rekmarks commented on packages/execution-environments/src/iframe/IFrameController.ts
> +export class IFrameController extends BaseController {
In line with the suggested renaming:

```suggestion
export class IFrameSnapExecutor extends BaseSnapExecutor {
```

2022-02-15 21:51 UTC, rekmarks commented on packages/execution-environments/src/web-workers/WebWorkerController.ts
> +export class WebWorkerController extends BaseController {
In line with the suggested renaming:

```suggestion
export class WebWorkerSnapExecutor extends BaseSnapExecutor {
```

2022-02-16 09:28 UTC, rekmarks commented
Previously, I suggested that we rename this package to `snap-executors` in my most recent review. On second thought, I think that's a bad idea, and the package itself should refer to "execution environments". I still think we should use names other than "controller" to refer to the classes that manage the execution of snaps inside of our execution environments, however.

2022-02-16 18:42 UTC, shanejonas commented on packages/execution-environments/src/web-workers/index.ts
> +import 'ses';
we shouldnt include this in the bundle see https://github.com/MetaMask/snaps-skunkworks/pull/231/files#r807333562

2022-02-23 07:28 UTC, rekmarks approved these changes
Excellent. LGTM!

2022-02-23 07:28 UTC, rekmarks commented on packages/execution-environments/src/common/BaseSnapExecutor.ts
> +      self?.addEventListener(
follow-up: We should fix the types such that `self` is always defined, if possible.

2022-02-25 16:13 UTC, rekmarks approved these changes

2022-02-25 16:14 UTC, merged