Add setInterval and clearInterval as default endowments
MetaMask/snaps-skunkworks pull request #326
Opened 2022-03-28 09:24 UTC by FrederikBolding

Fixes #299

2022-03-28 14:36 UTC, ritave requested changes

2022-03-28 14:36 UTC, ritave commented on packages/execution-environments/src/common/endowments/interval.ts
> +    // @todo Should we return a number that we decide for NodeJS?
handles could be just `unknown` (as well as `registeredIntervals = new Set<unknown>()` and everywhere else a handle is expected) and that would work for both browser and NodeJS environments

2022-03-28 14:36 UTC, ritave commented on packages/execution-environments/src/common/endowments/interval.ts
> +    // @todo Should we return a number that we decide for NodeJS?
Might as well make the same change to `setTimeout`

2022-03-29 00:50 UTC, rekmarks approved these changes
LGTM!

2022-03-29 10:38 UTC, ritave approved these changes

2022-03-29 10:39 UTC, merged