Bump electron to 15.5.5
MetaMask/snaps-skunkworks pull request #562
Opened 2022-06-20 07:58 UTC by Mrtenz

Supersedes #553.

This fixes some security vulnerabilities in Electron, as mentioned in #553. Dependabot somehow messed up the `yarn.lock` file in the original PR, so for this PR I just ran `yarn add -D electron@^15.5.5` from the main branch.

2022-06-20 09:20 UTC, FrederikBolding requested changes
Looks like tests run forever 😅

2022-06-20 17:52 UTC, rekmarks commented
It's very possible that the `jest` Electron runner we use is not compatible with this version of Electron, and I'm not sure if the runner is receiving regular updates.

2022-06-21 08:13 UTC, Mrtenz commented
It appears that [the Jest Electron runner we use](https://github.com/facebook-atom/jest-electron-runner) is archived. 😅

2022-06-21 10:10 UTC, Mrtenz commented
I tried an alternative test runner for Electron, but that doesn't seem to work either. It seems that the only reason for using Electron is support for web workers? If so, we could consider removing the web worker functionality, and test on the iframe instead. Unless we plan on using web workers in the future?

@rekmarks @FrederikBolding

2022-06-22 08:20 UTC, FrederikBolding commented
@Mrtenz Can you close this, create an issue writing up the work done and the conclusion that it doesn't work and close that issue too? Make sure to estimate that issue.

2022-06-22 09:09 UTC, closed without merging