Move eval functionality to utils package
MetaMask/snaps-skunkworks pull request #666
Opened 2022-08-03 13:07 UTC by Mrtenz

This moves eval functionality (`evalHandler` and dependencies) from the CLI package to the utils package. This makes it possible to integrate it into the bundler plugins in a future PR.

2022-08-14 22:16 UTC, rekmarks requested changes
I fixed a couple of things I noticed during local review, but otherwise nothing controversial going on here. Should be good to merge after resolving my nits and whatever's going on with the new `eval` test!

2022-08-14 22:16 UTC, rekmarks commented on packages/utils/src/eval-worker.ts
>  import 'ses/lockdown';
nit: I don't think we need to disable the rule for the entire file.

```suggestion
// eslint-disable-next-line import/no-unassigned-import	
import 'ses/lockdown';
```

2022-08-15 09:20 UTC, Mrtenz commented on packages/utils/src/fs.ts
> +    filename.indexOf('/') !== -1
Good point. Might be best to use `pathUtils.normalize(filename).indexOf(pathUtils.sep)`, in case someone using Windows uses the `/` separator?

2022-08-15 09:25 UTC, Mrtenz commented on packages/utils/src/fs.ts
> +    filename.indexOf('/') !== -1
This can be simplified more actually, `pathUtils.basename(filename) === filename`.

2022-08-16 21:40 UTC, rekmarks approved these changes
Ship it!

2022-08-16 22:08 UTC, merged