Fix update snap request object
MetaMask/snaps-skunkworks pull request #673
Opened 2022-08-05 22:07 UTC by hmalik88

See #672

2022-08-06 00:17 UTC, rekmarks submitted a review, later dismissed
LGTM!

2022-08-06 20:32 UTC, ritave approved these changes

2022-08-06 20:34 UTC, ritave requested changes
Actually, can you add a test that checks if the id's match in the main object / metadata?

2022-08-10 21:31 UTC, rekmarks approved these changes
LGTM!

2022-08-10 21:38 UTC, merged